// js/assistant.js

const BASE44_BASE_URL = "https://nullai.base44.app";
const BASE44_APP_ID = "6687ebfbbbaa7e8910eb4eb9";
const BASE44_API_KEY = "c00d41eb8e5c8e44ebae08764a75";

let activeChatSessionId = null;

/**
 * Initializes a clean chat log entry directly inside the Base44 system
 */
async function initializeBase44Chat() {
    try {
        const response = await fetch(`${BASE44_BASE_URL}/entities/Chat`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-app-id": BASE44_APP_ID,
                "api_key": BASE44_API_KEY
            },
            body: JSON.stringify({
                title: `Dashboard Session - ${new Date().toLocaleTimeString()}`,
                chat_type: "saved"
            })
        });

        if (!response.ok) throw new Error("Failed to initialize system session link.");
        
        const chatData = await response.json();
        // Capture the autogenerated ID created by Base44's backend schema
        activeChatSessionId = chatData.id;
        console.log("[NullAI] Session connected. Linked ID:", activeChatSessionId);
    } catch (err) {
        console.error("[NullAI Setup Error]:", err);
        // Fallback local structural ID string if network initialization hiccups
        activeChatSessionId = "fallback_" + Math.random().toString(36).substring(7);
    }
}

/**
 * Commits user inputs to Base44 and waits for the AI agent worker pipeline
 */
async function sendChatMessage(userText) {
    if (!activeChatSessionId) {
        await initializeBase44Chat();
    }

    try {
        // Post user item to the Message collection
        const userMsgResponse = await fetch(`${BASE44_BASE_URL}/entities/Message`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-app-id": BASE44_APP_ID,
                "api_key": BASE44_API_KEY
            },
            body: JSON.stringify({
                role: "user",
                content: userText,
                chat_id: activeChatSessionId
            })
        });

        if (!userMsgResponse.ok) throw new Error("Failed to sync message record.");

        // Wait briefly for Base44's integrated background agent worker to respond
        await new Promise(resolve => setTimeout(resolve, 1800));

        // Pull the updated dataset collection sorted by newest first
        const checkReplyResponse = await fetch(
            `${BASE44_BASE_URL}/entities/Message?chat_id=${activeChatSessionId}&sort=createdAt:desc&limit=2`,
            {
                method: "GET",
                headers: {
                    "x-app-id": BASE44_APP_ID,
                    "api_key": BASE44_API_KEY
                }
            }
        );

        if (!checkReplyResponse.ok) throw new Error("Failed to pull system responses.");

        const messages = await checkReplyResponse.json();
        
        // Return the fresh response text if generated by the assistant agent
        if (messages && messages.length > 0) {
            const latestMsg = messages[0];
            if (latestMsg.role === "assistant" || latestMsg.role === "agent") {
                return latestMsg.content;
            }
        }
        
        return "System processing query. Try asking again if the line remains idle.";

    } catch (error) {
        console.error("[NullAI Operational Fault]:", error);
        return "Connection timed out. Check back momentarily.";
    }
}
