window.__NX_ACH_CATALOG = [
    { id: 'welcome', title: 'Welcome Aboard', desc: 'Land on Null X.', icon: 'fa-rocket' },
    { id: 'trophy_case', title: 'Trophy Case', desc: 'Open the Achievements panel.', icon: 'fa-trophy' },
    { id: 'gamer', title: 'Boot Sequence', desc: 'Click a game card.', icon: 'fa-gamepad' },
    { id: 'collector', title: 'Collector', desc: 'Favorite a game.', icon: 'fa-star' },
    { id: 'lucky', title: 'Feeling Lucky', desc: 'Use Random Game.', icon: 'fa-shuffle' },
    { id: 'tuned', title: 'System Preferences', desc: 'Open Settings.', icon: 'fa-gear' },
    { id: 'ghost', title: 'Ghost Protocol', desc: 'Open Stealth Mode.', icon: 'fa-mask' },
    { id: 'social', title: 'Comms Online', desc: 'Open Communications / Chat.', icon: 'fa-comments' },
    { id: 'identity', title: 'Identity Check', desc: 'Open your Profile.', icon: 'fa-user' },
    { id: 'proxy', title: 'Bypass Engineer', desc: 'Open Unblockers.', icon: 'fa-shield-halved' },
    { id: 'searcher', title: 'Query Runner', desc: 'Search for a game.', icon: 'fa-magnifying-glass' },
    { id: 'calc_open', title: 'Number Cruncher', desc: 'Open the Calculator.', icon: 'fa-calculator' },
    { id: 'calc_use', title: 'Math Wizard', desc: 'Evaluate an expression in the Calculator.', icon: 'fa-square-root-variable' },
    { id: 'home_nav', title: 'Home Base', desc: 'Return to Home from another section.', icon: 'fa-house' },
    { id: 'games_nav', title: 'Arcade Access', desc: 'Open the Games section.', icon: 'fa-gamepad' },
    { id: 'favorites_nav', title: 'Hall of Fame', desc: 'Open Favorites.', icon: 'fa-star' },
    { id: 'featured_play', title: 'Spotlight', desc: 'Play the featured title.', icon: 'fa-play' },
    { id: 'signin_click', title: 'Front Desk', desc: 'Click Sign In.', icon: 'fa-right-to-bracket' },
    { id: 'cloud_export', title: 'Data Courier', desc: 'Use Export Save.', icon: 'fa-cloud-arrow-up' },
    { id: 'cloud_import', title: 'Data Recovery', desc: 'Use Import Save.', icon: 'fa-cloud-arrow-down' },
    { id: 'theme_change', title: 'Palette Swap', desc: 'Select a theme.', icon: 'fa-palette' },
    { id: 'session_5m', title: 'Settling In', desc: 'Stay on the site for 5 minutes.', icon: 'fa-clock' },
    { id: 'session_15m', title: 'Committed', desc: 'Stay on the site for 15 minutes.', icon: 'fa-hourglass-half' },
    { id: 'multi_section', title: 'Tourist', desc: 'Visit 4 different sections in one session.', icon: 'fa-map' },
    { id: 'search_empty', title: 'No Results Needed', desc: 'Clear the search bar after typing.', icon: 'fa-eraser' },
    { id: 'battery_check', title: 'Power Aware', desc: 'The battery widget loaded a reading.', icon: 'fa-battery-three-quarters' },
    { id: 'news_open', title: 'Bulletin Board', desc: 'Interact with System News.', icon: 'fa-newspaper' },
    { id: 'ctx_menu', title: 'Context Aware', desc: 'Open a game right-click menu.', icon: 'fa-computer-mouse' },
    { id: 'double_favorite', title: 'Encore', desc: 'Favorite two different games.', icon: 'fa-star' },
    { id: 'random_x3', title: 'Chaos Agent', desc: 'Hit Random Game three times.', icon: 'fa-dice' },
    { id: 'play_x5', title: 'Marathon Runner', desc: 'Launch five games.', icon: 'fa-person-running' },
    { id: 'settings_return', title: 'Back from Config', desc: 'Open Settings then return to the dashboard.', icon: 'fa-rotate-left' },
    { id: 'calculator_help', title: 'RTFM', desc: 'Type help in the Calculator.', icon: 'fa-book' },
    { id: 'calculator_clear', title: 'Clean Slate', desc: 'Type clear in the Calculator.', icon: 'fa-broom' },
    { id: 'power_user', title: 'Power User', desc: 'Unlock 15 achievements.', icon: 'fa-bolt' },
    { id: 'completionist_half', title: 'Halfway There', desc: 'Unlock half of all achievements.', icon: 'fa-flag-checkered' },
    { id: 'egg_konami', title: 'Classic Input', desc: 'You entered a sequence older than most of this site.', icon: 'fa-keyboard', secret: true, hint: 'An old console code still works somewhere on this page.' },
    { id: 'egg_logo', title: 'Persistent Clicker', desc: 'The logo finally admitted you exist.', icon: 'fa-hand-pointer', secret: true, hint: 'Something in the sidebar rewards patience.' },
    { id: 'egg_night', title: 'Night Shift', desc: 'You showed up while the rest of the world slept.', icon: 'fa-moon', secret: true, hint: 'Time of day matters.' },
    { id: 'egg_console', title: 'Under the Hood', desc: 'You talked to the site console.', icon: 'fa-terminal', secret: true, hint: 'There is a console on this page. Say hello.' },
    { id: 'egg_title', title: 'Triple Tap', desc: 'The greeting noticed your enthusiasm.', icon: 'fa-hand-point-up', secret: true, hint: 'The welcome text is more interactive than it looks.' },
    { id: 'egg_news', title: 'Archive Diver', desc: 'You scrolled deep into System News.', icon: 'fa-newspaper', secret: true, hint: 'History lives in the right rail.' },
    { id: 'egg_matrix', title: 'Follow the White Rabbit', desc: 'You found the green path.', icon: 'fa-code', secret: true, hint: 'A theme shares its name with a certain rain.' },
    { id: 'egg_pi', title: 'Circle Constant', desc: 'The calculator recognized a famous constant.', icon: 'fa-pie-chart', secret: true, hint: 'Compute something involving a classic circle number.' },
    { id: 'egg_42', title: 'Answer to Everything', desc: 'You computed the answer.', icon: 'fa-robot', secret: true, hint: 'Try a very famous small integer in the calculator.' },
    { id: 'egg_1337', title: 'Elite', desc: 'Leet recognized.', icon: 'fa-user-secret', secret: true, hint: 'A classic gamer number in the calculator.' },
    { id: 'egg_zero_div', title: 'Void Division', desc: 'You poked infinity.', icon: 'fa-divide', secret: true, hint: 'Ask the calculator to divide by nothing.' },
    { id: 'egg_double_click_logo', title: 'Echo', desc: 'The logo heard you twice quickly.', icon: 'fa-clone', secret: true, hint: 'Speed matters near the brand mark.' },
    { id: 'egg_long_search', title: 'Librarian', desc: 'Your search query was unusually long.', icon: 'fa-book-open', secret: true, hint: 'Type a very long search.' },
    { id: 'egg_idle', title: 'AFK Champion', desc: 'You left the tab alone for a while.', icon: 'fa-couch', secret: true, hint: 'Walk away and come back.' },
    { id: 'egg_rainbow', title: 'Prism', desc: 'You cycled through several themes quickly.', icon: 'fa-rainbow', secret: true, hint: 'Themes, but make it rapid.' },
    { id: 'egg_panic_key', title: 'Red Button Adjacent', desc: 'You touched a panic-related control.', icon: 'fa-exclamation', secret: true, hint: 'Settings holds emergency tools.' },
    { id: 'egg_fullscreen_attempt', title: 'Stage Lights', desc: 'You tried to go big.', icon: 'fa-expand', secret: true, hint: 'F11 is a lifestyle.' },
    { id: 'egg_copy', title: 'Clipboard Agent', desc: 'You copied something on the page.', icon: 'fa-copy', secret: true, hint: 'Select and copy.' },
    { id: 'egg_paste', title: 'Clipboard Return', desc: 'You pasted into a field.', icon: 'fa-paste', secret: true, hint: 'Ctrl+V somewhere useful.' },
    { id: 'egg_scroll_bottom', title: 'Depth Charge', desc: 'You scrolled the main content deeply.', icon: 'fa-arrow-down', secret: true, hint: 'Keep going down the page.' },
    { id: 'play_x10', title: 'Arcade Regular', desc: 'Launch ten games.', icon: 'fa-fire' },
    { id: 'play_x25', title: 'Arcade Legend', desc: 'Launch twenty-five games.', icon: 'fa-crown' },
    { id: 'random_x10', title: 'Entropy Max', desc: 'Hit Random Game ten times.', icon: 'fa-dice-d20' },
    { id: 'favorite_x5', title: 'Curator', desc: 'Favorite five different games.', icon: 'fa-stars' },
    { id: 'session_30m', title: 'Time Sink', desc: 'Stay on the site for 30 minutes.', icon: 'fa-hourglass-end' },
    { id: 'session_60m', title: 'True Believer', desc: 'Stay on the site for 60 minutes.', icon: 'fa-infinity' },
    { id: 'multi_section_all', title: 'Cartographer', desc: 'Visit every major section in one session.', icon: 'fa-globe' },
    { id: 'calc_ops_10', title: 'Equation Spammer', desc: 'Evaluate 10 expressions in the Calculator.', icon: 'fa-plus-minus' },
    { id: 'search_x5', title: 'Search Party', desc: 'Run five different searches.', icon: 'fa-magnifying-glass-plus' },
    { id: 'theme_x3', title: 'Style Hopper', desc: 'Change themes three times.', icon: 'fa-swatchbook' },
    { id: 'nav_settings_x3', title: 'Tinkerer', desc: 'Open Settings three times.', icon: 'fa-screwdriver-wrench' },
    { id: 'stealth_x2', title: 'Twice Invisible', desc: 'Open Stealth Mode twice.', icon: 'fa-user-ninja' },
    { id: 'chat_message', title: 'First Transmission', desc: 'Send something in Communications.', icon: 'fa-paper-plane' },
    { id: 'profile_edit', title: 'Identity Forge', desc: 'Change something on your Profile.', icon: 'fa-id-card' },
    { id: 'unblocker_open', title: 'Tunnel Vision', desc: 'Open an unblocker tool.', icon: 'fa-road' },
    { id: 'favorites_empty', title: 'Blank Slate', desc: 'Open Favorites while it is empty.', icon: 'fa-box-open' },
    { id: 'game_long_play', title: 'Immersed', desc: 'Keep a game open for 3 minutes.', icon: 'fa-couch' },
    { id: 'keyboard_nav', title: 'Hotkey Curious', desc: 'Use arrow keys while focused on the page.', icon: 'fa-arrows-up-down-left-right' },
    { id: 'resize_window', title: 'Responsive Soul', desc: 'Resize the browser window.', icon: 'fa-window-restore' },
    { id: 'dark_hours', title: 'After Hours', desc: 'Use the site between 10 PM and midnight.', icon: 'fa-cloud-moon' },
    { id: 'morning_user', title: 'Early Bird', desc: 'Use the site between 5 AM and 8 AM.', icon: 'fa-sun' },
    { id: 'weekend_warrior', title: 'Weekend Warrior', desc: 'Visit on a Saturday or Sunday.', icon: 'fa-calendar-week' },
    { id: 'power_user_25', title: 'Achievement Hunter', desc: 'Unlock 25 achievements.', icon: 'fa-medal' },
    { id: 'power_user_40', title: 'Completionist Path', desc: 'Unlock 40 achievements.', icon: 'fa-award' },
    { id: 'completionist_full', title: 'Null X Master', desc: 'Unlock every non-secret achievement.', icon: 'fa-trophy' },
    { id: 'first_error', title: 'Syntax Survivor', desc: 'Trigger a calculator error.', icon: 'fa-triangle-exclamation' },
    { id: 'calc_sqrt', title: 'Root Access', desc: 'Use sqrt in the Calculator.', icon: 'fa-square-root-variable' },
    { id: 'calc_trig', title: 'Angle of Attack', desc: 'Use a trig function in the Calculator.', icon: 'fa-wave-square' },
    { id: 'about_page', title: 'Lore Seeker', desc: 'Open the About section.', icon: 'fa-circle-info' },
    { id: 'tos_view', title: 'Fine Print', desc: 'Open Terms of Service.', icon: 'fa-file-contract' },
    { id: 'lockscreen_view', title: 'Gatekeeper', desc: 'Visit the Lockscreen page.', icon: 'fa-lock' },
    { id: 'custom_crosshair', title: 'Crosshair Crafter', desc: 'Open Custom Crosshair.', icon: 'fa-crosshairs' },
    { id: 'audio_interact', title: 'Sound Check', desc: 'Interact with an audio control.', icon: 'fa-volume-high' },
    { id: 'refresh_games', title: 'Reload Protocol', desc: 'Refresh or reload the games grid.', icon: 'fa-rotate' },
    { id: 'mobile_view', title: 'Pocket Pilot', desc: 'Use a narrow viewport under 600px.', icon: 'fa-mobile-screen' },
    { id: 'egg_konami_twice', title: 'Sequence Addict', desc: 'You entered the classic sequence again.', icon: 'fa-repeat', secret: true, hint: 'Some codes work more than once.' },
    { id: 'egg_logo_20', title: 'Logo Devotee', desc: 'You really love that logo.', icon: 'fa-heart', secret: true, hint: 'Patience, then more patience.' },
    { id: 'egg_calc_e', title: 'Natural Selection', desc: 'You used e in the calculator.', icon: 'fa-superscript', secret: true, hint: 'A famous irrational in the engine.' },
    { id: 'egg_calc_tau', title: 'Two Pi Club', desc: 'You preferred tau.', icon: 'fa-circle', secret: true, hint: 'Some say the true circle constant is twice as large.' },
    { id: 'egg_inspect', title: 'Inspector', desc: 'You opened DevTools-ish behavior.', icon: 'fa-magnifying-glass', secret: true, hint: 'Right-click the page background.' },
    { id: 'egg_rapid_click', title: 'Click Storm', desc: 'You clicked extremely fast.', icon: 'fa-bolt', secret: true, hint: 'Spam clicks anywhere for a second.' },
    { id: 'egg_tab_blur', title: 'Alt-Tab Survivor', desc: 'You left and came back quickly.', icon: 'fa-window-minimize', secret: true, hint: 'Switch away then return.' },
    { id: 'egg_spacebar', title: 'Space Cadet', desc: 'You mashed space a lot.', icon: 'fa-keyboard', secret: true, hint: 'The space bar is not just for jumping.' },
    { id: 'egg_hello_console', title: 'Hello World', desc: 'You typed hello into the console.', icon: 'fa-comment', secret: true, hint: 'Be polite to the terminal.' },
    { id: 'egg_null', title: 'Null Pointer', desc: 'You searched for null.', icon: 'fa-ban', secret: true, hint: 'Search the void.' },
    { id: 'egg_secret_word', title: 'Passphrase', desc: 'You typed a hidden word in search.', icon: 'fa-key', secret: true, hint: 'Try searching for the site name in lowercase.' },
    { id: 'egg_triple_escape', title: 'Escape Artist', desc: 'You hit Escape three times quickly.', icon: 'fa-person-running', secret: true, hint: 'Escape is a habit.' },
    { id: 'egg_zoom', title: 'Close Up', desc: 'You zoomed the page.', icon: 'fa-search-plus', secret: true, hint: 'Ctrl and scroll, or pinch.' },
    { id: 'egg_print', title: 'Hard Copy', desc: 'You tried to print the page.', icon: 'fa-print', secret: true, hint: 'Ctrl+P.' },
    { id: 'egg_select_all', title: 'Select Everything', desc: 'You selected all on the page.', icon: 'fa-i-cursor', secret: true, hint: 'Ctrl+A.' },
    { id: 'egg_middle_click', title: 'Third Button', desc: 'You middle-clicked something.', icon: 'fa-computer-mouse', secret: true, hint: 'The scroll wheel clicks too.' },
    { id: 'egg_drag', title: 'Drag Racer', desc: 'You dragged across the page.', icon: 'fa-hand', secret: true, hint: 'Click and drag somewhere boring.' },
    { id: 'egg_hash_nav', title: 'Fragment Hunter', desc: 'You used a URL hash.', icon: 'fa-hashtag', secret: true, hint: 'Add #something to the address bar.' },
    { id: 'egg_localstorage_peek', title: 'Storage Spy', desc: 'You touched achievement storage from outside.', icon: 'fa-database', secret: true, hint: 'Devs sometimes poke localStorage.' },
    { id: 'egg_uptime_day', title: 'Day One', desc: 'Your first unlock was over a day ago and you returned.', icon: 'fa-calendar-day', secret: true, hint: 'Come back tomorrow.' },
    { id: 'egg_all_secrets', title: 'Egg Hunter', desc: 'You unlocked many secret achievements.', icon: 'fa-egg', secret: true, hint: 'Secrets within secrets.' }
  ];
