let _0xData = [
  {id: "adofai", title: "ADOFAI", url: "../Games/ADOFAI/ADOFAI.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/ADOFAI/ADOFAI.jpeg" },
  {id: "aoc", title: "AOC", url: "../Games/AOC/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/AOC/images.jpeg" },
  {id: "asrp", title: "ASRP", url: "../Games/ASRP/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/ASRP/images (1).jpeg" },
  {id: "autoupdatefiletest", title: "Autoupdatefiletest", url: "../Games/Autoupdatefiletest/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Autoupdatefiletest/images (9).jpeg" },
  {id: "bsv", title: "BSV", url: "../Games/BSV/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/BSV/images (2).jpeg" },
  {id: "bitcoin", title: "Bitcoin", url: "../Games/Bitcoin/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Bitcoin/images (4).jpeg" },
  {id: "dbs", title: "DBS", url: "../Games/DBS/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/DBS/download.jpeg" },
  {id: "dogeminer1", title: "Dogeminer1", url: "../Games/Dogeminer1/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Dogeminer1/images (3).jpeg" },
  {id: "dogeminer2", title: "Dogeminer2", url: "../Games/Dogeminer2/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Dogeminer2/images (4).jpeg" },
  {id: "escaperoad", title: "Escaperoad", url: "../Games/Escaperoad/Escape Road/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Escaperoad/Escape Road/images (5).jpeg" },
  {id: "gamesavedata", title: "GameSaveData", url: "../Games/GameSaveData/GSD.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "gunmayhem", title: "GunMayhem", url: "../Games/GunMayhem/gunmayhem2/gunmayhem2.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/GunMayhem/gunmayhem2/images (10).jpeg" },
  {id: "ime", title: "IME", url: "../Games/IME/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/IME/images (12).jpeg" },
  {id: "imt", title: "IMT", url: "../Games/IMT/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/IMT/images (13).jpeg" },
  {id: "jebieak", title: "JEBIEAK", url: "../Games/JEBIEAK/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "motox3m", title: "MotoX3m", url: "../Games/MotoX3m/MotoX3m Pool Party/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/MotoX3m/MotoX3m Pool Party/images (19).jpeg" },
  {id: "sortthecourt", title: "Sortthecourt", url: "../Games/Sortthecourt/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Sortthecourt/index.apple-touch-icon.png" },
  {id: "tapa", title: "TAPA", url: "../Games/TAPA/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/TAPA/images (20).jpeg" },
  {id: "tapa2", title: "TAPA2", url: "../Games/TAPA2/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/TAPA2/images.png" },
  {id: "t_3sahurobby", title: "T^3sahurobby", url: "../Games/T^3sahurobby/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/T^3sahurobby/images (21).jpeg" },
  {id: "vex", title: "Vex", url: "../Games/Vex/Vexx3m2/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/Vex/Vex3/images (22).jpeg" },
  {id: "adarkroom", title: "adarkroom", url: "../Games/adarkroom/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/adarkroom/images (36).jpeg" },
  {id: "adatewithdeath", title: "adatewithdeath", url: "../Games/adatewithdeath/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/adatewithdeath/images.jpeg" },
  {id: "adventneon", title: "adventneon", url: "../Games/adventneon/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/adventneon/images (2).jpeg" },
  {id: "adventure_capitalist", title: "adventure capitalist", url: "../Games/adventure capitalist/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/adventure capitalist/images (3).jpeg" },
  {id: "agar", title: "agar", url: "../Games/agar/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "ahoysurvival", title: "ahoysurvival", url: "../Games/ahoysurvival/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/ahoysurvival/images (8).jpeg" },
  {id: "airline", title: "airline", url: "../Games/airline/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/airline/images (4).png" },
  {id: "amongus", title: "amongus", url: "../Games/amongus/Amongus.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/amongus/images (7).jpeg" },
  {id: "arenaking", title: "arenaking", url: "../Games/arenaking/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/arenaking/images (34).jpeg" },
  {id: "babeltower", title: "babeltower", url: "../Games/babeltower/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "backrooms", title: "backrooms", url: "../Games/backrooms/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "badbodyguard", title: "badbodyguard", url: "../Games/badbodyguard/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "bakonmaydie", title: "bakonmaydie", url: "../Games/bakonmaydie/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "baldisbasics", title: "baldisbasics", url: "../Games/baldisbasics/Baldisbasics.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "baseballbros", title: "baseballbros", url: "../Games/baseballbros/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/baseballbros/favicon.png" },
  {id: "basketballstars", title: "basketballstars", url: "../Games/basketballstars/Basketballstars.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/basketballstars/images (30).jpeg" },
  {id: "basketbros", title: "basketbros", url: "../Games/basketbros/Basketbros.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/basketbros/images (29).jpeg" },
  {id: "basketrandom", title: "basketrandom", url: "../Games/basketrandom/Basketrandom.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/basketrandom/images (5).jpeg" },
  {id: "bcadventure", title: "bcadventure", url: "../Games/bcadventure/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "bitplanes", title: "bitplanes", url: "../Games/bitplanes/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "brotatoapng", title: "brotatoAPNG", url: "../Games/brotatoAPNG/Brotato.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/brotatoAPNG/images (23).jpeg" },
  {id: "bulletforce", title: "bulletforce", url: "../Games/bulletforce/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/bulletforce/images (27).jpeg" },
  {id: "carcrash3", title: "carcrash3", url: "../Games/carcrash3/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "cookieclicker", title: "cookieclicker", url: "../Games/cookieclicker/cookieclicker.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/cookieclicker/images (35).jpeg" },
  {id: "daddish", title: "daddish", url: "../Games/daddish/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "dayintheoffice", title: "dayintheoffice", url: "../Games/dayintheoffice/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/dayintheoffice/images (1).jpeg" },
  {id: "dokidoki", title: "dokidoki", url: "../Games/dokidoki/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "drivemad", title: "drivemad", url: "../Games/drivemad/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/drivemad/images (26).jpeg" },
  {id: "eaglercraft", title: "eaglercraft", url: "../Games/eaglercraft/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "eggy", title: "eggy", url: "../Games/eggy/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "gunspin", title: "gunspin", url: "../Games/gunspin/gunspin.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "mutilateadoll", title: "mutilateadoll", url: "../Games/mutilateadoll/mutilateadoll.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "pokemon_emerald", title: "pokemon-emerald", url: "../Games/pokemon-emerald/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/pokemon-emerald/thumbnail.webp" },
  {id: "polytrack", title: "polytrack", url: "../Games/polytrack/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "ragdrop", title: "ragdrop", url: "../Games/ragdrop/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "retrobowl", title: "retrobowl", url: "../Games/retrobowl/Retrobowl.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/retrobowl/images (6).jpeg" },
  {id: "rocket", title: "rocket", url: "../Games/rocket/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "skibshooter", title: "skibshooter", url: "../Games/skibshooter/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "skinwalker", title: "skinwalker", url: "../Games/skinwalker/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "slicemaster", title: "slicemaster", url: "../Games/slicemaster/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "slope", title: "slope", url: "../Games/slope/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/slope/images (25).jpeg" },
  {id: "stickmerge", title: "stickmerge", url: "../Games/stickmerge/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/stickmerge/images (31).jpeg" },
  {id: "strikeforcekitty", title: "strikeforcekitty", url: "../Games/strikeforcekitty/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/strikeforcekitty/images (32).jpeg" },
  {id: "superhot", title: "superhot", url: "../Games/superhot/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/superhot/images (33).jpeg" },
  {id: "trucksim", title: "trucksim", url: "../Games/trucksim/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "tungbaldibasics", title: "tungbaldibasics", url: "../Games/tungbaldibasics/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "wordle", title: "wordle", url: "../Games/wordle/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true },
  {id: "yohoho", title: "yohoho", url: "../Games/yohoho/index.html", desc: "Coming soon. Edit this description in main.js.", popular: true, image: "../Games/yohoho/images (24).jpeg" },
];