export const cloaks = [
  {
    name: "Google Classroom",
    url: "https://classroom.google.com/",
    title: "Home",
    icon: "https://ssl.gstatic.com/classroom/ic_product_classroom_32.png",
  },
  {
    name: "Google Drive",
    url: "https://drive.google.com/",
    title: "My Drive - Google Drive",
    icon: "https://ssl.gstatic.com/images/branding/product/2x/hh_drive_36dp.png",
  },
  {
    name: "Gmail",
    url: "https://mail.google.com/",
    title: "Inbox (12) - Google Mail",
    icon: "https://www.gstatic.com/images/branding/product/2x/gmail_2020q4_512dp.png",
  },
  {
    name: "Canvas",
    url: "https://www.instructure.com/",
    title: "Dashboard",
    icon: "https://du11hjcvx0uqb.cloudfront.net/dist/images/favicon-e10d657a73.ico",
  },
  {
    name: "Canva",
    url: "https://www.canva.com/",
    title: "Home - Canva",
    icon: "https://static.canva.com/static/images/favicon.ico",
  },
  {
    name: "Microsoft 365",
    url: "https://m365.cloud.microsoft/search?from=PortalHome&auth=2&origindomain=microsoft365&client-request-id=8f00c2ca-b9d5-43f0-9056-d1cca74442ba",
    title: "Search | M365 Copilot",
    icon: "https://www.google.com/s2/favicons?sz=64&domain=microsoft.com",
  },
  {
    name: "NoRedInk",
    url: "https://www.noredink.com/learn/home",
    title: "Student Home | NoRedInk",
    icon: "https://www.noredink.com/favicon.ico",
  },
  {
    name: "Neptune Navigate",
    url: "https://universal.neptunenavigate.com/course/view/j6orc8CW0xCrSodEmuZ4rAMl32Ml32",
    title: "Universal - Portal",
    icon: "https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://universal.neptunenavigate.com&size=64",
  },
  {
    name: "Pear Assessment",
    url: "https://assessment.peardeck.com/home/assignments",
    title: "Assignments - Pear Assessment",
    icon: "https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://assessment.peardeck.com/home/assignments&size=64",
  },
  {
    name: "Membean",
    url: "https://membean.com/dashboard",
    title: "Dashboard",
    icon: "https://membean.com/favicon.ico",
  },
  {
    name: "i-Ready Reading",
    url: "https://login.i-ready.com/mspro/dashboard/home",
    title: "Reading Home Page, i-Ready",
    icon: "https://login.i-ready.com/favicon.ico",
  },
  {
    name: "i-Ready Math",
    url: "https://login.i-ready.com/mspro/dashboard/home",
    title: "Math Home Page, i-Ready",
    icon: "https://login.i-ready.com/favicon.ico",
  },
  {
    name: "DeltaMath",
    url: "https://www.deltamath.com/app/student/4796542/upcoming",
    title: "DeltaMath Student Application",
    icon: "https://www.deltamath.com/favicon.ico",
  },
  {
    name: "ExploreLearning Gizmos",
    url: "https://apps.explorelearning.com/gizmos?altRedirectID=0",
    title: "ExploreLearning Gizmos",
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://explorelearning.com&size=64",
  },
  {
    name: "Progress Learning",
    url: "https://app.progresslearning.com/classlink?code=c1774361678626941d7d1c9cfefa3f6fbd4cbdf674eca2&response_type=code",
    title: "Assignments | Progress Learning",
    icon: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://app.progresslearning.com/&size=64",
  },
  {
    name: "Student Support Time",
    url: "https://forsyth.studentsupporttime.com/SHome#!/app/dashboard",
    title: "Thrive - Dashboard",
    icon: "https://forsyth.studentsupporttime.com/favicon.ico",
  },
  {
    name: "Kahoot",
    url: "https://kahoot.it/",
    title: "Kahoot!",
    icon: "https://kahoot.it/favicon.ico",
  },
  {
    name: "Nearpod",
    url: "https://nearpod.com/student/",
    title: "Nearpod",
    icon: "https://nearpod.com/favicon.ico",
  },
  {
    name: "Khan Academy",
    url: "https://www.khanacademy.org/",
    title: "Khan Academy | Free Online Courses, Lessons & Practice",
    icon: "https://cdn.kastatic.org/images/khan-logo-dark-cropped.png",
  },
  {
    name: "Coursera",
    url: "https://www.coursera.org/",
    title: "Coursera | Online Courses & Credentials",
    icon: "https://d3njjcbhbojbot.cloudfront.net/web/images/favicons/apple-touch-icon-180x180.png",
  },
  {
    name: "edX",
    url: "https://www.edx.org/",
    title: "edX | Online Courses from the World's Best Universities",
    icon: "https://www.edx.org/favicon.ico",
  },
  {
    name: "Quizlet",
    url: "https://quizlet.com/",
    title: "Quizlet - Flashcards, Study Guides & More",
    icon: "https://quizlet.com/favicon.ico",
  },
  {
    name: "Grammarly",
    url: "https://www.grammarly.com/",
    title: "Grammarly: Free Writing AI Assistant",
    icon: "https://www.grammarly.com/favicon.ico",
  },
  {
    name: "Clever",
    url: "https://clever.com/",
    title: "Clever | Single Sign-On for Education",
    icon: "https://assets.clever.com/favicon.ico",
  },
  {
    name: "Blackboard",
    url: "https://www.blackboard.com/",
    title: "Blackboard | Education Delivery Platform",
    icon: "https://www.blackboard.com/favicon.ico",
  },
  {
    name: "Moodle",
    url: "https://moodle.org/",
    title: "Moodle - Open-source learning platform",
    icon: "https://moodle.org/theme/moodleorg/pix/favicon.ico",
  },
  {
    name: "Schoology",
    url: "https://www.schoology.com/",
    title: "Schoology - Learning Management System",
    icon: "https://www.schoology.com/favicon.ico",
  },
  {
    name: "Google Docs",
    url: "https://docs.google.com/",
    title: "Google Docs",
    icon: "https://ssl.gstatic.com/docs/documents/images/kix-favicon-2023q4-32x32.png",
  },
  {
    name: "Google Slides",
    url: "https://slides.google.com/",
    title: "Google Slides",
    icon: "https://ssl.gstatic.com/docs/presentation/images/kix-favicon-2023q4-32x32.png",
  },
  {
    name: "Google Sheets",
    url: "https://sheets.google.com/",
    title: "Google Sheets",
    icon: "https://ssl.gstatic.com/docs/spreadsheets/images/kix-favicon-2023q4-32x32.png",
  },
  {
    name: "IXL",
    url: "https://www.ixl.com/",
    title: "IXL | Math, Language Arts, Science, Social Studies",
    icon: "https://www.ixl.com/favicon.ico",
  },
  {
    name: "Prodigy",
    url: "https://www.prodigygame.com/",
    title: "Prodigy | Math Game for Students",
    icon: "https://www.prodigygame.com/favicon.ico",
  },
  {
    name: "BrainPOP",
    url: "https://www.brainpop.com/",
    title: "BrainPOP - Animated Educational Site",
    icon: "https://www.brainpop.com/favicon.ico",
  },
  {
    name: "PBS Kids",
    url: "https://pbskids.org/",
    title: "PBS KIDS",
    icon: "https://pbskids.org/favicon.ico",
  },
  {
    name: "Starfall",
    url: "https://www.starfall.com/",
    title: "Starfall Education: Learn to Read",
    icon: "https://www.starfall.com/favicon.ico",
  },
  {
    name: "ABCmouse",
    url: "https://www.abcmouse.com/",
    title: "ABCmouse.com - Early Learning Academy",
    icon: "https://www.abcmouse.com/favicon.ico",
  },
  {
    name: "Duolingo",
    url: "https://www.duolingo.com/",
    title: "Duolingo - The world's best way to learn a language",
    icon: "https://d2.duolingo.com/favicon.ico",
  },
  {
    name: "Code.org",
    url: "https://code.org/",
    title: "Code.org - Learn Computer Science",
    icon: "https://code.org/favicon.ico",
  },
  {
    name: "Scholastic",
    url: "https://www.scholastic.com/",
    title: "Scholastic | Books for Kids",
    icon: "https://www.scholastic.com/favicon.ico",
  },
  {
    name: "National Geographic Kids",
    url: "https://kids.nationalgeographic.com/",
    title: "National Geographic Kids",
    icon: "https://www.nationalgeographic.com/favicon.ico",
  },
  {
    name: "Wolfram Alpha",
    url: "https://www.wolframalpha.com/",
    title: "Wolfram|Alpha: Computational Knowledge Engine",
    icon: "https://www.wolframalpha.com/favicon.ico",
  },
  {
    name: "Chegg",
    url: "https://www.chegg.com/",
    title: "Chegg - Get 24/7 Homework Help",
    icon: "https://www.chegg.com/favicon.ico",
  },
  {
    name: "Pearson",
    url: "https://www.pearson.com/",
    title: "Pearson | The world's learning company",
    icon: "https://www.pearson.com/favicon.ico",
  },
  {
    name: "Houghton Mifflin Harcourt",
    url: "https://www.hmhco.com/",
    title: "HMH | Education Resources",
    icon: "https://www.hmhco.com/favicon.ico",
  },
  {
    name: "McGraw Hill",
    url: "https://www.mheducation.com/",
    title: "McGraw Hill - Education",
    icon: "https://www.mheducation.com/favicon.ico",
  },
  {
    name: "Desmos",
    url: "https://www.desmos.com/",
    title: "Desmos | Graphing Calculator",
    icon: "https://www.desmos.com/favicon.ico",
  },
  {
    name: "CK-12",
    url: "https://www.ck12.org/",
    title: "CK-12 Foundation",
    icon: "https://www.ck12.org/favicon.ico",
  },
  {
    name: "TED-Ed",
    url: "https://ed.ted.com/",
    title: "TED-Ed | Lessons Worth Sharing",
    icon: "https://ed.ted.com/favicon.ico",
  },
  {
    name: "Britannica",
    url: "https://www.britannica.com/",
    title: "Encyclopædia Britannica",
    icon: "https://www.britannica.com/favicon.ico",
  },
  {
    name: "Smithsonian Learning Lab",
    url: "https://learninglab.si.edu/",
    title: "Smithsonian Learning Lab",
    icon: "https://learninglab.si.edu/favicon.ico",
  },
  {
    name: "Common App",
    url: "https://www.commonapp.org/",
    title: "Common App | Apply to College",
    icon: "https://www.commonapp.org/favicon.ico",
  },
  {
    name: "College Board",
    url: "https://www.collegeboard.org/",
    title: "College Board - SAT, AP, College Search",
    icon: "https://www.collegeboard.org/favicon.ico",
  },
  {
    name: "Khan Academy Kids",
    url: "https://www.khanacademy.org/khan-academy-kids",
    title: "Khan Academy Kids - Free Educational App",
    icon: "https://cdn.kastatic.org/images/khan-logo-dark-cropped.png",
  },
  {
    name: "SplashLearn",
    url: "https://www.splashlearn.com/",
    title: "SplashLearn - Fun Math & ELA Learning",
    icon: "https://www.splashlearn.com/favicon.ico",
  },
  {
    name: "Quizizz",
    url: "https://quizizz.com/",
    title: "Quizizz | Make Learning Fun",
    icon: "https://quizizz.com/favicon.ico",
  },
  {
    name: "Edpuzzle",
    url: "https://edpuzzle.com/",
    title: "Edpuzzle - Make Any Video Your Lesson",
    icon: "https://edpuzzle.com/favicon.ico",
  },
  {
    name: "Notion",
    url: "https://www.notion.so/",
    title: "Notion - All-in-one Workspace",
    icon: "https://www.notion.so/favicon.ico",
  },
  {
    name: "OpenStax",
    url: "https://openstax.org/",
    title: "OpenStax - Free Textbooks",
    icon: "https://openstax.org/favicon.ico",
  },
  {
    name: "Crash Course",
    url: "https://thecrashcourse.com/",
    title: "Crash Course",
    icon: "https://thecrashcourse.com/favicon.ico",
  },
  {
    name: "BBC Bitesize",
    url: "https://www.bbc.co.uk/bitesize",
    title: "BBC Bitesize - Learning Resources",
    icon: "https://www.bbc.co.uk/favicon.ico",
  },
  {
    name: "Skillshare",
    url: "https://www.skillshare.com/",
    title: "Skillshare - Online Classes",
    icon: "https://www.skillshare.com/favicon.ico",
  },
  {
    name: "Udemy",
    url: "https://www.udemy.com/",
    title: "Udemy - Online Courses",
    icon: "https://www.udemy.com/favicon.ico",
  },
  {
    name: "LinkedIn Learning",
    url: "https://www.linkedin.com/learning/",
    title: "LinkedIn Learning",
    icon: "https://www.linkedin.com/favicon.ico",
  },
  {
    name: "Harvard Online",
    url: "https://online.harvard.edu/",
    title: "Harvard Online Courses",
    icon: "https://online.harvard.edu/favicon.ico",
  },
  {
    name: "Mystery Science",
    url: "https://mysteryscience.com/",
    title: "Mystery Science",
    icon: "https://mysteryscience.com/favicon.ico",
  },
  {
    name: "Reading IQ",
    url: "https://www.readingiq.com/",
    title: "ReadingIQ - Digital Library",
    icon: "https://www.readingiq.com/favicon.ico",
  },
  {
    name: "CodeSpark",
    url: "https://codespark.org/",
    title: "codeSpark Academy",
    icon: "https://codespark.org/favicon.ico",
  },
  {
    name: "Brighterly",
    url: "https://brighterly.com/",
    title: "Brighterly - Math for Kids",
    icon: "https://brighterly.com/favicon.ico",
  },
  {
    name: "Storynory",
    url: "https://www.storynory.com/",
    title: "Storynory - Free Audio Stories",
    icon: "https://www.storynory.com/favicon.ico",
  },
  {
    name: "CoolMath",
    url: "https://www.coolmath.com/",
    title: "Cool Math Games & Lessons",
    icon: "https://www.coolmath.com/favicon.ico",
  },
  {
    name: "DOGOnews",
    url: "https://www.dogonews.com/",
    title: "DOGOnews - Kid News",
    icon: "https://www.dogonews.com/favicon.ico",
  },
  {
    name: "Brainscape",
    url: "https://www.brainscape.com/",
    title: "Brainscape - Flashcards",
    icon: "https://www.brainscape.com/favicon.ico",
  },
  {
    name: "Piazza",
    url: "https://piazza.com/",
    title: "Piazza - Q&A Platform",
    icon: "https://piazza.com/favicon.ico",
  },
  {
    name: "Quizalize",
    url: "https://www.quizalize.com/",
    title: "Quizalize - Adaptive Quizzes",
    icon: "https://www.quizalize.com/favicon.ico",
  },
  {
    name: "Classkick",
    url: "https://www.classkick.com/",
    title: "Classkick - Real-time Feedback",
    icon: "https://www.classkick.com/favicon.ico",
  },
  {
    name: "Peergrade",
    url: "https://www.peergrade.io/",
    title: "Peergrade - Peer Assessment",
    icon: "https://www.peergrade.io/favicon.ico",
  },
  {
    name: "Open Yale Courses",
    url: "https://oyc.yale.edu/",
    title: "Open Yale Courses",
    icon: "https://oyc.yale.edu/favicon.ico",
  },
  {
    name: "MIT OpenCourseWare",
    url: "https://ocw.mit.edu/",
    title: "MIT OpenCourseWare",
    icon: "https://ocw.mit.edu/favicon.ico",
  },
  {
    name: "FutureLearn",
    url: "https://www.futurelearn.com/",
    title: "FutureLearn - Online Courses",
    icon: "https://www.futurelearn.com/favicon.ico",
  },
  {
    name: "MasterClass",
    url: "https://www.masterclass.com/",
    title: "MasterClass - Learn from the Best",
    icon: "https://www.masterclass.com/favicon.ico",
  },
  {
    name: "Codecademy",
    url: "https://www.codecademy.com/",
    title: "Codecademy - Learn to Code",
    icon: "https://www.codecademy.com/favicon.ico",
  },
  {
    name: "freeCodeCamp",
    url: "https://www.freecodecamp.org/",
    title: "freeCodeCamp.org",
    icon: "https://www.freecodecamp.org/favicon.ico",
  },
  {
    name: "Tynker",
    url: "https://www.tynker.com/",
    title: "Tynker - Coding for Kids",
    icon: "https://www.tynker.com/favicon.ico",
  },
  {
    name: "Outschool",
    url: "https://outschool.com/",
    title: "Outschool - Online Classes",
    icon: "https://outschool.com/favicon.ico",
  },
  {
    name: "XtraMath",
    url: "https://xtramath.org/",
    title: "XtraMath - Math Fact Practice",
    icon: "https://xtramath.org/favicon.ico",
  },
  {
    name: "Raz-Kids",
    url: "https://www.raz-kids.com/",
    title: "Raz-Kids - Online Reading",
    icon: "https://www.raz-kids.com/favicon.ico",
  },
  {
    name: "Epic!",
    url: "https://www.getepic.com/",
    title: "Epic! - Digital Library",
    icon: "https://www.getepic.com/favicon.ico",
  },
  {
    name: "DreamBox",
    url: "https://www.dreambox.com/",
    title: "DreamBox Learning",
    icon: "https://www.dreambox.com/favicon.ico",
  },
  {
    name: "ST Math",
    url: "https://www.stmath.com/",
    title: "ST Math - Visual Math Program",
    icon: "https://www.stmath.com/favicon.ico",
  },
  {
    name: "Zearn",
    url: "https://www.zearn.org/",
    title: "Zearn Math",
    icon: "https://www.zearn.org/favicon.ico",
  },
  {
    name: "NoRedInk",
    url: "https://www.noredink.com/",
    title: "NoRedInk - Writing Practice",
    icon: "https://www.noredink.com/favicon.ico",
  },
  {
    name: "Newsela",
    url: "https://newsela.com/",
    title: "Newsela - Differentiated Reading",
    icon: "https://newsela.com/favicon.ico",
  },
  {
    name: "CommonLit",
    url: "https://www.commonlit.org/",
    title: "CommonLit - Free Reading Program",
    icon: "https://www.commonlit.org/favicon.ico",
  },
  {
    name: "ReadWorks",
    url: "https://www.readworks.org/",
    title: "ReadWorks - Reading Comprehension",
    icon: "https://www.readworks.org/favicon.ico",
  },
  {
    name: "Achieve the Core",
    url: "https://achievethecore.org/",
    title: "Achieve the Core",
    icon: "https://achievethecore.org/favicon.ico",
  },
  {
    name: "Illustrative Mathematics",
    url: "https://illustrativemathematics.org/",
    title: "Illustrative Mathematics",
    icon: "https://illustrativemathematics.org/favicon.ico",
  },
  {
    name: "PhET Simulations",
    url: "https://phet.colorado.edu/",
    title: "PhET Interactive Simulations",
    icon: "https://phet.colorado.edu/favicon.ico",
  },
  {
    name: "GeoGebra",
    url: "https://www.geogebra.org/",
    title: "GeoGebra - Math & Science Tools",
    icon: "https://www.geogebra.org/favicon.ico",
  },
  {
    name: "Wolfram MathWorld",
    url: "https://mathworld.wolfram.com/",
    title: "Wolfram MathWorld",
    icon: "https://mathworld.wolfram.com/favicon.ico",
  },
  {
    name: "SparkNotes",
    url: "https://www.sparknotes.com/",
    title: "SparkNotes - Study Guides",
    icon: "https://www.sparknotes.com/favicon.ico",
  },
  {
    name: "CliffsNotes",
    url: "https://www.cliffsnotes.com/",
    title: "CliffsNotes - Study Guides",
    icon: "https://www.cliffsnotes.com/favicon.ico",
  },
  {
    name: "Bartleby",
    url: "https://www.bartleby.com/",
    title: "Bartleby - Homework Help",
    icon: "https://www.bartleby.com/favicon.ico",
  },
];
export function applyCloak(cloakName) {
  const selected = cloaks.find(c => c.name === cloakName);
  if (selected) {
    document.title = selected.title;
    let link = document.querySelector("link[rel*='icon']") || document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = selected.icon;
    document.getElementsByTagName('head')[0].appendChild(link);
    localStorage.setItem('savedCloak', cloakName);
  }
}
